name: Revision de Python

on: [push] # Se activa cada vez que subes código

jobs:
  build:
    runs-on: ubuntu-latest # Usa Linux en la nube de GitHub (gratis)

    steps:
    - uses: actions/checkout@v3 # Descarga tu código en esa PC virtual

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Revisar errores de sintaxis
      run: |
        python -m py_compile *.py 
        echo "✅ ¡Todo el código de hoy está perfecto!"